version: '3'
services:
  builder:
    container_name: angular2-jsonapi
    image: ubuntu24.04-node-22-angular2-jsonapi
    network_mode: 'host'
    volumes:
      - .:/home/ubuntu/angular2-jsonapi
    stdin_open: true
    tty: true
    env_file:
      - .env
